### ISSUE TITLE
expire_time stamp problem

### ISSUE THREAD

**Issue by mazdakdev** [staliox/pyxui#11]
It seems,  there is a bug for **expire_time** field. it doesn't matter what you pass to it as long as it in unix time/epoch format, 
the **Expire date** shown in **XUI**  would always be something around **1970**.

<img width="1215" alt="Screenshot 2023-06-25 at 1 39 17 PM" src="https://github.com/staliox/pyxui/assets/60855141/5c35193d-d33b-4d74-8c99-400538aa9be9">

```python
xui.add_client(email="dsds@msddjd.dsdd", inbound_id=3,   uuid="5d3d1bac-49cd-4b66-8be9-a728efa2d05ea",  enable = True,  flow = "", expi
re_time=1687687706)
```

**Comment by staliox** [comment]
> It seems, there is a bug for **expire_time** field. it doesn't matter what you pass to it as long as it in unix time/epoch format, the **Expire date** shown in **XUI** would always be something around **1970**.
> 
> <img alt="Screenshot 2023-06-25 at 1 39 17 PM" width="1215" src="https://user-images.githubusercontent.com/60855141/248547016-5c35193d-d33b-4d74-8c99-400538aa9be9.png">
> ```python
> xui.add_client(email="dsds@msddjd.dsdd", inbound_id=3,   uuid="5d3d1bac-49cd-4b66-8be9-a728efa2d05ea",  enable = True,  flow = "", expi
> re_time=1687687706)
> ```

as xui timestamp, you must not pass 10 digit timestamp
use this formular:

`timestmap * 1000`

**Comment by mazdakdev** [comment]
Thank you for your solution, it worked.
I'm closing this issue.
