### ISSUE TITLE
expire_time

### ISSUE THREAD

**Issue by roozbeh-m03** [staliox/pyxui#18]
سلام وقتتون بخیر، expire_time توی این ماژور چطور کار میکنه؟ چطور میتونم محاسبه کنم؟ چون هرچی میزنم یه اروری میده
ممنون

**Comment by staliox** [comment]
با سلام
دقت کنید که پارامتر expire_time باید timestamp باشه و حتما 13 رقمی (شامل میلی ثانیه) باید باشه
مثال برای timestamp یک ماه آینده:

`from datetime import datetime, timedelta

current_date = datetime.now()

next_month_date = datetime(current_date.year, current_date.month, 1) + timedelta(days=30)
next_month_timestamp = int(next_month_date.timestamp()) * 1000

print(next_month_timestamp) # 1710620239000
`

**Comment by staliox** [comment]
> سلام وقتتون بخیر، expire_time توی این ماژور چطور کار میکنه؟ چطور میتونم محاسبه کنم؟ چون هرچی میزنم یه اروری میده ممنون

با سلام
دقت کنید که پارامتر expire_time باید timestamp باشه و حتما 13 رقمی (شامل میلی ثانیه) باید باشه
مثال برای timestamp یک ماه آینده:

```python
from datetime import datetime, timedelta

current_date = datetime.now()

next_month_date = datetime(current_date.year, current_date.month, 1) + timedelta(days=30)
next_month_timestamp = int(next_month_date.timestamp()) * 1000

print(next_month_timestamp) # 1710620239000
```

**Comment by roozbeh-m03** [comment]
واقعا ممنون از شما 😍❤️

**Comment by roozbeh-m03** [comment]
بعد میشه بگید چطور میتونم تایم باقیمونده یه سرویس یا کانفیگ رو از روی تایم اسمپ اکسپایری حساب کنم؟
ببخشید اذیت میکنما
