### ISSUE TITLE
محدودیت یوزر

### ISSUE THREAD

**Issue by ramtiny** [staliox/pyxui#20]
سلام وقت بخیر
الان میشه محدودیت یوزر داشت ؟

**Comment by staliox** [comment]
سلام، محدودیت یوزر یا همون آیپی، مربوط به پنلی هست که استفاده میکنید و فکر میکنم که داخل پنل sanaei هم قابل استفاده هست فقط، توضیحاتشم داخل گیت هاب ایشون باید موجود باشه قطعا

> سلام وقت بخیر الان میشه محدودیت یوزر داشت ؟

**Comment by ramtiny** [comment]
کسی تاحالا استفاده کرده و نتیجه گرفته باشه ؟

**Comment by staliox** [comment]
@ramtiny > کسی تاحالا استفاده کرده و نتیجه گرفته باشه ؟

https://github.com/MHSanaei/3x-ui?tab=readme-ov-file#ip-limit
