### ISSUE TITLE
ارور BadLogin 

### ISSUE THREAD

**Issue by mahdi14541380** [staliox/pyxui#23]
در پنل علیرضا موقع لوگین کردن ارور BadLoginلوگین دریافت میکنم در صورتی که پنل ثنایی این ارورو نمیده

**Comment by l3lack-eyes** [comment]
درسته

**Comment by staliox** [comment]
کتابخونه بروزرسانی شد.
`pip install -U pyxui`

**Comment by Aliw7979** [comment]
با آپدیت کردن پنل سنایی این مشکل دوباره به بوجود اومد.
