### ISSUE TITLE
Not Found هنگام اد کردن کلاینت

### ISSUE THREAD

**Issue by LingoMan2** [staliox/pyxui#24]
درود بر شما بنده مشکل در اضافه کردن کلاینت دارم
به من داره میگه not found با این حال که inbound id درسته و یکیه با پنل

**Comment by Tlauros** [comment]
جناب لطف میکنید دلیل complete چی بوده چون من از get_client اسفتاده میکنم با توجه به این که inboound , email , uuid درستع خروجی : An error occurred: [NOT_FOUND] Error 404 has been received  نمایش میده
