### ISSUE TITLE
"Delete client" function not working

### ISSUE THREAD

**Issue by Medi2ray** [staliox/pyxui#3]
Unfortunately, the "Delete client" feature does not work according to usage and an error occurs.

**Comment by Medi2ray** [comment]
For example, inside the delete_client function, one of the arguments is called 'inbound_id', but you called it 'id' in README.md in the usage section.

**Comment by staliox** [comment]
> For example, inside the delete_client function, one of the arguments is called 'inbound_id', but you called it 'id' in README.md in the usage section.

yeah i forgot that to update parameters name, now it's ok
but about delete_client method, make sure you use the latest version of alireza or sanaei xui panel and download repository again, i've changed a little thing
