### ISSUE TITLE
cant install package with pip

### ISSUE THREAD

**Issue by mmzeynaligh** [staliox/pyxui#4]
i update pip to last version, but when i try install and import package, i have an error:
ERROR: Could not find a version that satisfies the requirement pyxui (from versions: none)
ERROR: No matching distribution found for pyxui
tnx for your guide

**Comment by staliox** [comment]
> i update pip to last version, but when i try install and import package, i have an error: ERROR: Could not find a version that satisfies the requirement pyxui (from versions: none) ERROR: No matching distribution found for pyxui tnx for your guide

thanks for ur report
fixed now!

**Comment by mmzeynaligh** [comment]
tnx for attention, this problem is solved
but i have another question, can you generate function to saved all config in txt file?! or function to create handle for all function, I try to convey my meaning better with photos
![image](https://user-images.githubusercontent.com/64749378/235990771-8c715bb3-7d5a-4909-a671-1ead92ad28cf.png)
export config in this picture

**Comment by staliox** [comment]
@mmzeynaligh doesn't need to any specific func
just fetch all clients with get_inbounds
however I endeavor to incorporate this feature

**Comment by staliox** [comment]
> tnx for attention, this problem is solved but i have another question, can you generate function to saved all config in txt file?! or function to create handle for all function, I try to convey my meaning better with photos ![image](https://user-images.githubusercontent.com/64749378/235990771-8c715bb3-7d5a-4909-a671-1ead92ad28cf.png) export config in this picture

doesn't need to any specific func
just fetch all clients with `get_inbounds` method
however I endeavor to incorporate this feature
