### ISSUE TITLE
pachage have deep problem :)

### ISSUE THREAD

**Issue by mmzeynaligh** [staliox/pyxui#5]
![image](https://user-images.githubusercontent.com/64749378/236320156-31e3f749-2853-4bfc-92c5-29f29def1ef8.png)
we have some problem, in package file, i run python file for login in panel and get_inbouds, but we have some errors for packages file.

**Comment by staliox** [comment]
> ![image](https://user-images.githubusercontent.com/64749378/236320156-31e3f749-2853-4bfc-92c5-29f29def1ef8.png) we have some problem, in package file, i run python file for login in panel and get_inbouds, but we have some errors for packages file.

solved:
`pip install -U pyxui`
