### ISSUE TITLE
Login session

### ISSUE THREAD

**Issue by Moamethic** [staliox/pyxui#7]
Hi
Does this package save login sessions or should we authenticate every time?
If yes, does sessions have expire time limit?
Thanks

**Comment by staliox** [comment]
hola, each time you run this, it will login again
however you could login in your panel with your browser one time and take session cookie from your browser then do this:
`xui = XUI(address, port, session_string="SESSION")`

**Comment by staliox** [comment]
> Hi Does this package save login sessions or should we authenticate every time? If yes, does sessions have expire time limit? Thanks

hola, each time you run this, it will login again
however you could login in your panel with your browser one time and take session cookie from your browser then do this:
`xui = XUI(address, port, session_string="SESSION")`
