### ISSUE TITLE
افزودن امکان اپدیت کلاینت

### ISSUE THREAD

**Issue by ma1999** [staliox/pyxui#9]
سلام خیلی مفیده کتابخونه که درست کردید 
فقط بیزحمت امکان آپدیت کردن کلاینت رو هم اضافه کنید کامل تر میشه

**Comment by staliox** [comment]
> سلام خیلی مفیده کتابخونه که درست کردید فقط بیزحمت امکان آپدیت کردن کلاینت رو هم اضافه کنید کامل تر میشه

سلام
تو آپدیت جدید اضافه شد
`pip install -U pyxui`
